"""
Library Assistant — RAG-powered Streamlit app (simple, clean theme).

Upload PDF documents (catalog guides, borrowing policies, opening
hours, membership info, notices) in the sidebar, build the knowledge
base, then ask questions in the chat box. Answers are generated by
Llama 3 hosted on Groq, grounded only in the documents you uploaded.

Run with:
    streamlit run app.py

Prereqs:
    A free Groq API key set as GROQ_API_KEY in Streamlit secrets
    (or as an environment variable when running locally).
"""

import os
import tempfile
from datetime import datetime

import streamlit as st

from rag_core import (
    load_and_split_pdfs,
    build_vectorstore,
    load_vectorstore,
    build_rag_chain,
    answer_question,
    INDEX_DIR,
    OLLAMA_MODEL,
)

st.set_page_config(
    page_title="Library Assistant",
    page_icon="📚",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------
# Theme — simple and clean: flat surfaces, one accent color, thin
# borders, no gradients/blur/animation.
# ---------------------------------------------------------------------
st.markdown(
    """
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">

    <style>
        :root {
            --primary:      #1f6b47;
            --primary-dark: #17573b;
            --ink:          #1f2328;
            --ink-soft:     #6b7280;
            --bg:           #faf9f6;
            --surface:      #ffffff;
            --border:       #e5e2da;
            --warn:         #b45309;
        }

        html, body, [class*="css"] {
            font-family: "Inter", -apple-system, sans-serif;
        }

        [data-testid="stAppViewContainer"] { background: var(--bg); }
        [data-testid="stHeader"] { background: transparent; }
        .block-container { padding-top: 2.2rem; max-width: 1000px; }

        /* ---------- hero ---------- */
        .hero-card {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 12px;
            padding: 1.6rem 1.8rem;
            margin-bottom: 1.2rem;
            display: flex; justify-content: space-between; align-items: center;
            gap: 1.5rem; flex-wrap: wrap;
        }
        .hero-eyebrow {
            display: inline-flex; align-items: center; gap: 0.4rem;
            font-size: 0.72rem; font-weight: 600; letter-spacing: 0.04em;
            padding: 0.25rem 0.65rem; border-radius: 6px;
            background: var(--primary);
            color: white; text-transform: uppercase; margin-bottom: 0.7rem;
        }
        .hero-title {
            font-weight: 700;
            font-size: 2rem;
            line-height: 1.15;
            margin: 0 0 0.4rem 0;
            color: var(--ink);
        }
        .hero-sub {
            font-size: 0.9rem; color: var(--ink-soft);
            max-width: 560px; line-height: 1.5; margin: 0;
        }
        .stat-box {
            display: flex; flex-direction: column; gap: 0.3rem;
            background: var(--bg);
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 0.8rem 1.1rem;
            min-width: 190px;
        }
        .stat-box .num {
            font-weight: 700; font-size: 1.2rem; color: var(--ink);
        }
        .stat-box .lbl { font-size: 0.72rem; color: var(--ink-soft); }
        .stat-box .num span { color: var(--primary); }

        /* ---------- sidebar ---------- */
        section[data-testid="stSidebar"] {
            background: var(--surface);
            border-right: 1px solid var(--border);
        }
        section[data-testid="stSidebar"] .block-container { padding-top: 1.6rem; }
        section[data-testid="stSidebar"] h2, section[data-testid="stSidebar"] h3 {
            font-weight: 700; color: var(--ink);
        }
        section[data-testid="stSidebar"] p, section[data-testid="stSidebar"] label,
        section[data-testid="stSidebar"] .stCaption {
            color: var(--ink-soft) !important; font-size: 0.84rem !important;
        }

        .status-chip {
            display: inline-flex; align-items: center; gap: 0.5rem;
            background: var(--bg);
            border: 1px solid var(--border);
            border-radius: 999px;
            padding: 0.35rem 0.8rem;
            font-size: 0.76rem; font-weight: 600; color: var(--ink);
            margin-bottom: 1.1rem;
        }
        .status-chip .dot { width: 7px; height: 7px; border-radius: 50%; }
        .status-chip .dot.on  { background: var(--primary); }
        .status-chip .dot.off { background: var(--warn); }

        .catalog-card {
            background: var(--bg);
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 0.8rem 1rem;
            font-size: 0.82rem;
            color: var(--ink-soft);
            margin-bottom: 1rem;
        }
        .catalog-card b { color: var(--ink); }
        .catalog-card ul { margin: 0.4rem 0 0 1.1rem; padding: 0; }
        .catalog-card li { margin-bottom: 0.15rem; }

        /* file uploader */
        [data-testid="stFileUploaderDropzone"] {
            background: var(--bg);
            border: 1.5px dashed var(--border) !important;
            border-radius: 10px;
        }
        [data-testid="stFileUploaderDropzone"]:hover {
            border-color: var(--primary) !important;
        }

        /* buttons */
        .stButton > button {
            border-radius: 8px;
            border: 1px solid var(--border);
            background: var(--surface);
            color: var(--ink);
            font-weight: 600;
            font-size: 0.85rem;
            padding: 0.5rem 1rem;
        }
        .stButton > button:hover {
            border-color: var(--primary);
            color: var(--primary);
        }
        .stButton > button[kind="primary"] {
            background: var(--primary);
            border: 1px solid var(--primary);
            color: white;
        }
        .stButton > button[kind="primary"]:hover {
            background: var(--primary-dark);
            border-color: var(--primary-dark);
            color: white;
        }

        hr { border-color: var(--border) !important; }

        /* ---------- empty state ---------- */
        .empty-card {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 12px;
            padding: 2.6rem 2rem;
            text-align: center;
            margin-bottom: 1.2rem;
        }
        .empty-icon {
            width: 52px; height: 52px; border-radius: 50%;
            background: var(--primary);
            display: flex; align-items: center; justify-content: center;
            font-size: 1.4rem; margin: 0 auto 1rem auto;
        }
        .empty-title {
            font-weight: 700;
            font-size: 1.3rem; color: var(--ink); margin-bottom: 0.5rem;
        }
        .empty-body {
            font-size: 0.88rem; color: var(--ink-soft);
            max-width: 460px; margin: 0 auto 1.2rem auto; line-height: 1.6;
        }
        .step-pills { display: flex; justify-content: center; gap: 0.5rem; flex-wrap: wrap; }
        .step-pill {
            border: 1px solid var(--border);
            background: var(--bg);
            border-radius: 999px;
            padding: 0.4rem 0.9rem;
            font-size: 0.76rem; font-weight: 600; color: var(--ink);
        }

        /* ---------- chat ---------- */
        [data-testid="stChatMessage"] {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 10px;
            padding: 0.4rem 0.5rem;
            margin-bottom: 0.6rem;
        }
        [data-testid="stChatMessageAvatarUser"] {
            background: var(--ink-soft) !important;
        }
        [data-testid="stChatMessageAvatarAssistant"] {
            background: var(--primary) !important;
        }

        [data-testid="stChatInput"] {
            border-radius: 10px;
        }
        [data-testid="stChatInput"] textarea {
            border-radius: 10px !important;
            border: 1px solid var(--border) !important;
            background: var(--surface) !important;
            color: var(--ink) !important;
        }
        [data-testid="stChatInput"] textarea:focus {
            border-color: var(--primary) !important;
        }
        [data-testid="stChatInput"] button {
            background: var(--primary) !important;
            border-radius: 8px !important;
        }

        details {
            border-radius: 8px !important;
            border: 1px solid var(--border) !important;
            background: var(--surface);
        }
        summary { font-size: 0.8rem !important; color: var(--ink-soft) !important; font-weight: 600 !important; }

        [data-testid="stAlert"] { border-radius: 8px; font-size: 0.85rem; }

        ::-webkit-scrollbar { width: 8px; height: 8px; }
        ::-webkit-scrollbar-thumb {
            background: var(--border);
            border-radius: 8px;
        }
    </style>
    """,
    unsafe_allow_html=True,
)

# ---------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------
if "chain" not in st.session_state:
    st.session_state.chain = None
    st.session_state.retriever = None
if "messages" not in st.session_state:
    st.session_state.messages = []
if "catalog_sources" not in st.session_state:
    st.session_state.catalog_sources = []
if "chunk_count" not in st.session_state:
    st.session_state.chunk_count = 0
if "indexed_at" not in st.session_state:
    st.session_state.indexed_at = None


def _register_index(vectorstore):
    """Pull catalog stats out of a built/loaded vector store for the UI."""
    docs = getattr(vectorstore, "documents", [])
    sources = sorted({d.metadata.get("source", "unknown") for d in docs})
    st.session_state.catalog_sources = sources
    st.session_state.chunk_count = len(docs)
    st.session_state.indexed_at = datetime.now().strftime("%b %d, %I:%M %p")


def _has_api_key() -> bool:
    key = st.secrets.get("GROQ_API_KEY", None) if hasattr(st, "secrets") else None
    return bool(key or os.environ.get("GROQ_API_KEY"))


# ---------------------------------------------------------------------
# Hero
# ---------------------------------------------------------------------
doc_count = len(st.session_state.catalog_sources)

st.markdown(
    f"""
    <div class="hero-card">
        <div>
            <div class="hero-eyebrow">📚 Library Assistant</div>
            <div class="hero-title">Ask anything about the library</div>
            <p class="hero-sub">Grounded answers pulled from your library's catalog guides,
            borrowing policies, and notices — powered by Llama ({OLLAMA_MODEL} via Groq).</p>
        </div>
        <div class="stat-box">
            <div class="lbl">Knowledge base</div>
            <div class="num"><span>{st.session_state.chunk_count}</span> chunks · <span>{doc_count}</span> doc{"s" if doc_count != 1 else ""}</div>
            <div class="lbl">Last indexed {st.session_state.indexed_at or "— not yet —"}</div>
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

st.caption("Answers are grounded only in the documents you upload.")

# ---------------------------------------------------------------------
# Sidebar: build / load knowledge base
# ---------------------------------------------------------------------
with st.sidebar:
    conn_ok = _has_api_key()
    dot_cls = "on" if conn_ok else "off"
    conn_text = "Connected via Groq" if conn_ok else "No API key set"
    st.markdown(
        f'<div class="status-chip"><span class="dot {dot_cls}"></span>{conn_text}</div>',
        unsafe_allow_html=True,
    )

    st.markdown("### 📚 Library Documents")

    if st.session_state.catalog_sources:
        items = "".join(f"<li>{s}</li>" for s in st.session_state.catalog_sources)
        st.markdown(
            f'<div class="catalog-card"><b>Indexed now</b><ul>{items}</ul></div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            '<div class="catalog-card">No documents indexed yet — upload a library PDF below to get started.</div>',
            unsafe_allow_html=True,
        )

    uploaded_files = st.file_uploader(
        "Upload library PDFs (catalog guides, policies, notices)",
        type=["pdf"],
        accept_multiple_files=True,
    )

    col1, col2 = st.columns(2)
    with col1:
        build_clicked = st.button("Build Index", type="primary", use_container_width=True)
    with col2:
        load_clicked = st.button("Load Saved", use_container_width=True)

    k = st.slider("Chunks to retrieve per question", 2, 8, 4)

    if build_clicked:
        if not uploaded_files:
            st.warning("Please upload at least one PDF first.")
        else:
            with st.spinner("Reading PDFs, chunking, and embedding..."):
                tmp_paths = []
                tmp_dir = tempfile.mkdtemp()
                for f in uploaded_files:
                    path = os.path.join(tmp_dir, f.name)
                    with open(path, "wb") as out:
                        out.write(f.getbuffer())
                    tmp_paths.append(path)

                chunks = load_and_split_pdfs(tmp_paths)
                vectorstore = build_vectorstore(chunks)
                try:
                    chain, retriever = build_rag_chain(vectorstore, k=k)
                    st.session_state.chain = chain
                    st.session_state.retriever = retriever
                    _register_index(vectorstore)
                except RuntimeError as e:
                    st.error(str(e))
                    st.stop()
            st.success(f"Index built from {len(uploaded_files)} file(s), {len(chunks)} chunks.")
            st.rerun()

    if load_clicked:
        if not os.path.exists(INDEX_DIR):
            st.warning("No saved index found yet. Build one first.")
        else:
            with st.spinner("Loading saved index..."):
                vectorstore = load_vectorstore()
                try:
                    chain, retriever = build_rag_chain(vectorstore, k=k)
                    st.session_state.chain = chain
                    st.session_state.retriever = retriever
                    _register_index(vectorstore)
                except RuntimeError as e:
                    st.error(str(e))
                    st.stop()
            st.success("Saved index loaded.")
            st.rerun()

    st.divider()
    st.caption(
        "Rebuild whenever you add or change documents. The index is saved to "
        "disk too, so you can reload it next time without re-uploading."
    )

# ---------------------------------------------------------------------
# Main: empty state or chat interface
# ---------------------------------------------------------------------
if st.session_state.chain is None and not st.session_state.messages:
    st.markdown(
        """
        <div class="empty-card">
            <div class="empty-icon">📚</div>
            <div class="empty-title">Let's set up your library assistant</div>
            <div class="empty-body">
                Upload a catalog guide, borrowing policy, or library notice into the
                sidebar and build the index — everything's chunked and embedded right
                here. Then ask away and get answers grounded only in what you uploaded,
                sources included.
            </div>
            <div class="step-pills">
                <span class="step-pill">1 · upload a PDF</span>
                <span class="step-pill">2 · build the index</span>
                <span class="step-pill">3 · start asking</span>
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )

for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

question = st.chat_input("Ask about books, hours, memberships, policies...")

if question:
    if st.session_state.chain is None:
        st.error("Please build or load the knowledge base first (see sidebar).")
    else:
        st.session_state.messages.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                answer, sources = answer_question(
                    st.session_state.chain, st.session_state.retriever, question
                )
                st.markdown(answer)

                with st.expander("📄 Sources"):
                    for i, doc in enumerate(sources, 1):
                        st.markdown(
                            f"**{i}. {doc.metadata.get('source', 'unknown')}** "
                            f"(page {doc.metadata.get('page', '?')})"
                        )
                        st.caption(doc.page_content[:300] + "...")

        st.session_state.messages.append({"role": "assistant", "content": answer})
