"""
Student Management RAG Assistant — Streamlit app.

Upload PDF documents (handbooks, notices, circulars, records) in the
sidebar, build the knowledge base, then ask questions in the chat box.
Answers are generated by Llama 3 hosted on Groq, grounded only in the
documents you uploaded.

Run with:
    streamlit run app.py

Prereqs:
    A free Groq API key set as GROQ_API_KEY in Streamlit secrets
    (or as an environment variable when running locally).
"""

import os
import tempfile

import streamlit as st

from rag_core import (
    load_and_split_pdfs,
    build_vectorstore,
    load_vectorstore,
    build_rag_chain,
    answer_question,
    INDEX_DIR,
    OLLAMA_MODEL,
)

st.set_page_config(page_title="Student Management Assistant", page_icon="🎓")
st.title("🎓 Student Management RAG Assistant")
st.caption(f"Powered by Llama ({OLLAMA_MODEL} via Groq) — answers grounded in your documents")

# ---------------------------------------------------------------------
# Session state
# ---------------------------------------------------------------------
if "chain" not in st.session_state:
    st.session_state.chain = None
    st.session_state.retriever = None
if "messages" not in st.session_state:
    st.session_state.messages = []

# ---------------------------------------------------------------------
# Sidebar: build / load knowledge base
# ---------------------------------------------------------------------
with st.sidebar:
    st.header("📄 Knowledge Base")

    uploaded_files = st.file_uploader(
        "Upload student-related PDFs (handbooks, notices, etc.)",
        type=["pdf"],
        accept_multiple_files=True,
    )

    col1, col2 = st.columns(2)
    with col1:
        build_clicked = st.button("Build / Rebuild Index", type="primary")
    with col2:
        load_clicked = st.button("Load Saved Index")

    k = st.slider("Chunks to retrieve per question", 2, 8, 4)

    if build_clicked:
        if not uploaded_files:
            st.warning("Please upload at least one PDF first.")
        else:
            with st.spinner("Reading PDFs, chunking, and embedding..."):
                tmp_paths = []
                tmp_dir = tempfile.mkdtemp()
                for f in uploaded_files:
                    path = os.path.join(tmp_dir, f.name)
                    with open(path, "wb") as out:
                        out.write(f.getbuffer())
                    tmp_paths.append(path)

                chunks = load_and_split_pdfs(tmp_paths)
                vectorstore = build_vectorstore(chunks)
                try:
                    chain, retriever = build_rag_chain(vectorstore, k=k)
                    st.session_state.chain = chain
                    st.session_state.retriever = retriever
                except RuntimeError as e:
                    st.error(str(e))
                    st.stop()
            st.success(f"Index built from {len(uploaded_files)} file(s), {len(chunks)} chunks.")

    if load_clicked:
        if not os.path.exists(INDEX_DIR):
            st.warning("No saved index found yet. Build one first.")
        else:
            with st.spinner("Loading saved index..."):
                vectorstore = load_vectorstore()
                try:
                    chain, retriever = build_rag_chain(vectorstore, k=k)
                    st.session_state.chain = chain
                    st.session_state.retriever = retriever
                except RuntimeError as e:
                    st.error(str(e))
                    st.stop()
            st.success("Saved index loaded.")

    st.divider()
    st.caption(
        "Tip: rebuild the index whenever you add or change documents. "
        "The index is also saved to disk so you can reload it next time "
        "without re-uploading."
    )

# ---------------------------------------------------------------------
# Main: chat interface
# ---------------------------------------------------------------------
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.markdown(msg["content"])

question = st.chat_input("Ask about student policies, deadlines, fees, rules...")

if question:
    if st.session_state.chain is None:
        st.error("Please build or load the knowledge base first (see sidebar).")
    else:
        st.session_state.messages.append({"role": "user", "content": question})
        with st.chat_message("user"):
            st.markdown(question)

        with st.chat_message("assistant"):
            with st.spinner("Thinking..."):
                answer, sources = answer_question(
                    st.session_state.chain, st.session_state.retriever, question
                )
                st.markdown(answer)

                with st.expander("📚 Sources used"):
                    for i, doc in enumerate(sources, 1):
                        st.markdown(
                            f"**{i}. {doc.metadata.get('source', 'unknown')}** "
                            f"(page {doc.metadata.get('page', '?')})"
                        )
                        st.caption(doc.page_content[:300] + "...")

        st.session_state.messages.append({"role": "assistant", "content": answer})
